const languages = {
  eng: {
    "for-business": "for business",
    "download-app": "download app",
    h1: "Stay connected, wherever you are",
    p1: "Vorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "find-my-powerbank": "Find My Power Bank",
    "phase-1": "on the bus station",
    "phase-2": "in the shop",
    "phase-3": "in the SPA",
    "phase-4": "in the shopping mall",
    "phase-5": "at the airport",
    "phase-6": "on the beach",
    "phase-7": "at the park",
    "phase-8": "in the office",
    "phase-9": "in the coffee shop",
    "phase-10": "on the train",
    "phase-11": "in the library",
    "phase-12": "at the gym",
    "phase-13": "in the movie theater",
    "phase-14": "at the restaurant",
    "phase-15": "in the museum",
    "phase-16": "at the concert hall",
    "phase-17": "on the mountain top",
    "phase-18": "at the festival",
    "phase-19": "at the hotel lobby",
    "phase-20": "on a boat",
    "get-the-app__span": "Get the app",
    "get-the-app__h2": "Get the App and Never Run Out of Battery",
    "get-the-app__p2":
      "Download the app now to easily locate nearby power banks and keep your devices charged wherever you are!",
    "how-it-works": "How It Works",
    hiw__h3_1: "Download the app",
    hiw__p2_1: "Install our app on your device.",
    hiw__h3_2: "Find and scan",
    hiw__p2_1:
      "Use the map in the app to locate a nearby power bank and scan the QR code.",
    hiw__h3_3: "Rent the power bank",
    hiw__p2_3: "Select the power bank you need and rent it via the app.",
    hiw__h3_4: "Use and return",
    hiw__p2_4:
      "Use the power bank and return it to the nearest station when you're done.",
    hiw__span: "Affordable Rental Plans",
    hiw__h2: "Simple Pricing, No Hidden Fees",
    price__h3_1: "First Hour",
    "price__price-itself_1": "Free",
    price__subtext_1: "*Free for new users after registration",
    price__h3_2: "After 1 Hour",
    "per-hour": "/per hour",
    popular: "popular",
    price__h3_3: "Full Day",
    "per-day": "/per day",
    wmud__span: "What Makes Us Different",
    wmud__h3_1: "Convenient Locations",
    wmud__p2_1:
      "Find power banks at stations conveniently located throughout the city.",
    wmud__h3_2: "User-Friendly App",
    wmud__p2_2:
      "Easily locate, rent, and return power banks in just a few taps.",
    wmud__h3_3: "High-Quality Devices",
    wmud__p2_3:
      "Our power banks are reliable, fast-charging, and compatible with most devices",
    wmud__h3_4: "Affordable Pricing",
    wmud__p2_4:
      "Enjoy flexible rental plans that fit your needs, with no hidden fees.",
    map__span: "Map of Stations",
    map__h2: "Find the Nearest Charging Station",
    map__p2:
      "Easily find all nearby power bank stations and stay powered up wherever you are!",
    map__btn: "Find Stations Near Me",
    "download-app__h2": "Battery boost at the cost of a bottle of water",
    "download-app__p2":
      "Quick, easy, and budget-friendly – download the app to stay connected",
    "slider__h3-1": "Secure Payments",
    "slider__p-1": "Make quick and safe payments directly through the app.",
    "slider__h3-2": "User-Friendly Interface",
    "slider__p-2":
      "Easily rent, track, and return power banks with a simple app design.",
    "slider__h3-3": "Real-Time Tracking",
    "slider__p-3":
      "Know exactly where to find a station at any moment with our live map.",
    "slider__h3-4": "Exclusive Deals",
    "slider__p-4": "Enjoy discounts and perks available only for app users.",
    "slider__h3-5": "Sustainable Solution",
    "slider__p-5":
      " Choose eco-friendly reusable power banks to help reduce waste.",
  },
  pl: {
    "for-business": "dla biznesu",
    "download-app": "pobierz aplikację",
    h1: "Stay connected, wherever you are PL",
    p1: "Vorem ipsum dolor sit amet, consectetur adipiscing elit. PL",
    "find-my-powerbank": "Find My Power Bank PL",
    "phase-1": "na stacji autobusowej",
    "phase-2": "w sklepie",
    "phase-3": "w SPA",
    "phase-4": "w centrum handlowym",
    "phase-5": "na lotnisku",
    "phase-6": "na plaży",
    "phase-7": "w parku",
    "phase-8": "w biurze",
    "phase-9": "w kawiarni",
    "phase-10": "w pociągu",
    "phase-11": "w bibliotece",
    "phase-12": "na siłowni",
    "phase-13": "w kinie",
    "phase-14": "w restauracji",
    "phase-15": "w muzeum",
    "phase-16": "w sali koncertowej",
    "phase-17": "na szczycie góry",
    "phase-18": "na festiwalu",
    "phase-19": "w hotelu",
    "phase-20": "na łodzi",
    "get-the-app__span": "Get the app PL",
    "get-the-app__h2": "Get the App and Never Run Out of Battery PL",
    "get-the-app__p2":
      "Download the app now to easily locate nearby power banks and keep your devices charged wherever you are! PL",
    "how-it-works": "How It Works PL",
    hiw__h3_1: "Download the app PL",
    hiw__p2_1: "Install our app on your device. PL",
    hiw__h3_2: "Find and scan PL",
    hiw__p2_1:
      "Use the map in the app to locate a nearby power bank and scan the QR code. PL",
    hiw__h3_3: "Rent the power bank PL",
    hiw__p2_3: "Select the power bank you need and rent it via the app. PL",
    hiw__h3_4: "Use and return PL",
    hiw__p2_4:
      "Use the power bank and return it to the nearest station when you're done. PL",
    hiw__span: "Affordable Rental Plans PL",
    hiw__h2: "Simple Pricing, No Hidden Fees PL",
    price__h3_1: "First Hour PL",
    "price__price-itself_1": "Free PL",
    price__subtext_1: "*Free for new users after registration PL",
    price__h3_2: "After 1 Hour PL",
    "per-hour": "/per hour PL",
    popular: "popular PL",
    price__h3_3: "Full Day PL",
    "per-day": "/per day PL",
    wmud__span: "What Makes Us Different PL",
    wmud__h3_1: "Convenient Locations PL",
    wmud__p2_1:
      "Find power banks at stations conveniently located throughout the city. PL",
    wmud__h3_2: "User-Friendly App PL",
    wmud__p2_2:
      "Easily locate, rent, and return power banks in just a few taps. PL",
    wmud__h3_3: "High-Quality Devices PL",
    wmud__p2_3:
      "Our power banks are reliable, fast-charging, and compatible with most devices PL",
    wmud__h3_4: "Affordable Pricing PL",
    wmud__p2_4:
      "Enjoy flexible rental plans that fit your needs, with no hidden fees. PL",
    map__span: "Map of Stations PL",
    map__h2: "Find the Nearest Charging Station PL",
    map__p2:
      "Easily find all nearby power bank stations and stay powered up wherever you are! PL",
    map__btn: "Find Stations Near Me PL",
    "download-app__h2": "Battery boost at the cost of a bottle of water PL",
    "download-app__p2":
      "Quick, easy, and budget-friendly – download the app to stay connected PL",
    "slider__h3-1": "Secure Payments PL",
    "slider__p-1": "Make quick and safe payments directly through the app. PL",
    "slider__h3-2": "User-Friendly Interface PL",
    "slider__p-2":
      "Easily rent, track, and return power banks with a simple app design. PL",
    "slider__h3-3": "Real-Time Tracking PL",
    "slider__p-3":
      "Know exactly where to find a station at any moment with our live map. PL",
    "slider__h3-4": "Exclusive Deals PL",
    "slider__p-4": "Enjoy discounts and perks available only for app users. PL",
    "slider__h3-5": "Sustainable Solution PL",
    "slider__p-5":
      " Choose eco-friendly reusable power banks to help reduce waste. PL",
  },
};
